reviews-css-mob
Oleksandr-Karnaushenko/Project-group-8 pull request #10
Opened 2024-02-08 13:03 UTC by kasjanchykn

2024-02-08 13:08 UTC, Oleksandr-Karnaushenko commented on .gitignore
цей файл не чіпаємо, потрібно сворити собі в корені файл pullrequests-list.txt і уже в нього додаються всі пули

2024-02-08 13:14 UTC, Oleksandr-Karnaushenko commented on src/partials/reviews.html
після секції дати дів з класом container а то фсьо в нього обгорнути

2024-02-08 13:16 UTC, Oleksandr-Karnaushenko commented on src/css/reviews.css
> +@media screen and (min-width: 375px) {
прибрати, то нам дає глобальний клас container
і взагалі не чіпаємо container))

2024-02-08 13:16 UTC, Oleksandr-Karnaushenko requested changes
need some fix

2024-02-08 13:18 UTC, kasjanchykn commented on .gitignore
ок

2024-02-08 13:19 UTC, kasjanchykn commented on src/partials/reviews.html
ок, зрозуміла. дякую

2024-02-09 00:05 UTC, Oleksandr-Karnaushenko approved these changes

2024-02-09 00:06 UTC, merged