Header html css 1280
Oleksandr-Karnaushenko/Project-group-8 pull request #18
Opened 2024-02-08 21:51 UTC by Geraaa13

2024-02-09 01:19 UTC, Oleksandr-Karnaushenko commented on src/partials/header.html
>  <header class="header container">
container дай до header-wrapper
<!-- Header socials --> дописати href є у ТЗ

2024-02-09 01:22 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
>  .header {
mobile-first

2024-02-09 01:23 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  font-family: 'Inter', sans-serif;
наслідуєш з мейна, не потрібно тут писати

2024-02-09 01:23 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  font-family: 'Inter', sans-serif;
те саме

2024-02-09 01:24 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +.header-socials-link {
особисто мені мій ментор під час курсу казав задавати розміри у html

2024-02-09 01:25 UTC, Oleksandr-Karnaushenko requested changes
на доопрацювання

2024-02-09 15:51 UTC, Geraaa13 commented on src/partials/header.html
>  <header class="header container">
+

2024-02-09 15:52 UTC, Geraaa13 commented on src/css/header.css
>  .header {
okay

2024-02-09 16:33 UTC, Geraaa13 commented on src/css/header.css
> +.header-socials-link {
не зовсім розумію, що маєш на увазі. в html там задані розміри svg, a в css це розмір a

2024-02-09 22:44 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  width: 335px;
width: 335px; - забираємо, вбивця респонсивності

2024-02-09 22:46 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
>  }
@media only screen and (max-width: 375px) {
  .header-container {
    max-width: 335px; /**/
  }
}
додай це медіа, щоб у тебе була задана ширина білого фону

2024-02-09 22:47 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +@media only screen and (min-width: 768px) {
оці 2 медіа не потрібні, тобі то дасть глобальний клас контейнер

2024-02-09 22:47 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  width: 100%;
width: 100%; він і так 100%

2024-02-09 22:49 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  padding-top: 4px;
padding-top: 4px; - пофіксили вище

2024-02-09 22:49 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  width: 91px;
width: 91px; старайся робити через max-width: 91px;

2024-02-09 22:50 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +.header-socials {
padding-top: 12px;
  padding-bottom: 12px;
прибираємо, пофіксили перед цим

2024-02-09 22:51 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +@media only screen and (max-width: 767.98px) {
навіть страшно питати чому саме 767.98px ))

2024-02-09 22:54 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
твій код дуже нечитабельний
спочатку пропиши усі класи для мобайл
потім даєш один єдиний @media only screen and (min-width: ...px) і записуєш зміни, ну і так далі усі медіа
бо бігати по всьому css у пошуках який стиль зараз застовано важко, а це всього 143 стрічки коду

2024-02-09 22:55 UTC, Oleksandr-Karnaushenko commented on src/partials/header.html
> +  <div class="header-container container">
.container потрібно витягти в окремий дів після header і весь контент обгорнути в нього

2024-02-09 22:55 UTC, Oleksandr-Karnaushenko requested changes
на доопрацювання

2024-02-10 21:24 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +
.header > .container {
  padding-top: 20px;
}
це твій відступ, пам'ятай щоб його змінити на планшеті

2024-02-10 21:25 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +  margin: 0;
margin: 0; він наче нічого ж не дає

2024-02-10 21:25 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +@media only screen and (max-width: 375px) {
оце медіа в кінець коду до усих медіа

2024-02-10 21:27 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +@media only screen and (max-width: 767.98px) {
768 і вниз до усих медіа

2024-02-10 21:27 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +@media only screen and (max-width: 767.98px) {
768 і вниз

2024-02-10 21:28 UTC, Oleksandr-Karnaushenko commented on src/css/header.css
> +/* Tablet 768px */
не треба 3шт медіа, усе пиши в одному

2024-02-10 21:30 UTC, Oleksandr-Karnaushenko commented on src/partials/header.html
> +    <div class="mobile-menu is-open">
для себе роби, але на останньому коміті прибери is-open, бо якщо я залию то зіпсуємо усю картинку.
я для своїх тестів потім його відкрию

2024-02-10 21:31 UTC, Oleksandr-Karnaushenko requested changes
Усі медіа вниз і однакові об'єднати в 1
додати пару фіксів
прибрати клас перед пушом в html

2024-02-11 12:16 UTC, Oleksandr-Karnaushenko approved these changes
Фікси в наступній гілці

2024-02-11 12:16 UTC, merged