add html-css for mobile & images
Oleksandr-Karnaushenko/Project-group-8 pull request #2
Opened 2024-02-07 17:29 UTC by YanaDrozdova

2024-02-07 21:01 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
>  .our-yachts {
це потрібно прибрати.
колір, ширину та маржини будуть з .контейнера
падінги ми поки що не ставимо

2024-02-07 21:01 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
> +.container {}
Цей клас взагалі не чіпаємо, він глобальний

2024-02-07 21:02 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
>  }
це потрібно прибрати.
колір, ширину та маржини будуть з .контейнера
падінги ми поки що не ставимо

2024-02-07 21:02 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
>  .our-yachts {
це потрібно прибрати.
колір, ширину та маржини будуть з .контейнера
падінги ми поки що не ставимо

2024-02-07 21:03 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
>  .our-yachts {
це потрібно прибрати.
колір, ширину та маржини будуть з .контейнера
падінги ми поки що не ставимо

2024-02-07 21:06 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
> +.our-yachts-title {
max-width ми також наслідуємо з .контейнера
margin: 0 auto 40px; - здається вистачить тільки дати боттом 40

2024-02-07 21:11 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
> +.our-yachts-list-content {
ідентичний код як у .our-yachts-list-features, я б то дав одним класом .our-yachts-list

2024-02-07 21:16 UTC, Oleksandr-Karnaushenko commented on src/css/our-yachts.css
> +.our-yachts-content-item-text {
5 строчок дублювання коду, дати загальні стилі вище, а там де необхідно щось змінювати
padding-right: 16px; тут та padding-left: 16px; в .our-yachts-features-item-text я б теж дав у .our-yachts-lists

2024-02-07 21:24 UTC, Oleksandr-Karnaushenko requested changes
Потрібно прибрати деякі класи та усунути дублювання

2024-02-08 09:29 UTC, Oleksandr-Karnaushenko approved these changes
good job

2024-02-08 09:50 UTC, tanyf5 commented on src/partials/our-yachts.html
> +<section class="our-yachts">
please add the id for section

2024-02-08 09:53 UTC, tanyf5 reviewed
please add an id for section

2024-02-08 11:00 UTC, tanyf5 approved these changes

2024-02-08 11:17 UTC, merged