Add hero html
Oleksandr-Karnaushenko/Project-group-8 pull request #3
Opened 2024-02-07 18:24 UTC by gorisgor

Додав текст секції в hero html

2024-02-07 21:37 UTC, Oleksandr-Karnaushenko commented on src/css/hero.css
>  .hero {
маржин ми унаслідуємо від .container
height: 100vh; майже ніколи не вказується

2024-02-07 21:37 UTC, Oleksandr-Karnaushenko commented on src/css/hero.css
> +.container {
цей клас не чіпаємо, він глобальний

2024-02-07 21:39 UTC, Oleksandr-Karnaushenko commented on src/css/hero.css
> +  padding-top: 198px;
padding-top: 198px; поки що прибираємо

2024-02-07 21:42 UTC, Oleksandr-Karnaushenko commented on src/partials/hero.html
> +    <a href="rent-yacht" class="hero-link">Yacht rental</a>
href="rent-yacht" # перед rent-yacht

2024-02-07 21:42 UTC, Oleksandr-Karnaushenko commented on src/partials/hero.html
> +  <h1 class="hero-title">
після секції усе потрібно обгорнути в div та перенести клас container туди

2024-02-07 21:42 UTC, Oleksandr-Karnaushenko commented on src/css/hero.css
> +  font-family: 'Inter', sans-serif;
фонт наслідується, він у нас 'Inter' по всій сторінці

2024-02-07 21:44 UTC, Oleksandr-Karnaushenko requested changes
Потрібно декілька змін

2024-02-08 04:59 UTC, gorisgor commented on src/css/hero.css
>  .hero {
прибрав

2024-02-08 04:59 UTC, gorisgor commented on src/css/hero.css
> +.container {
не чіпаю, прибрав

2024-02-08 05:00 UTC, gorisgor commented on src/css/hero.css
> +  padding-top: 198px;
прибрав

2024-02-08 05:00 UTC, gorisgor commented on src/partials/hero.html
> +    <a href="rent-yacht" class="hero-link">Yacht rental</a>
додав

2024-02-08 05:00 UTC, gorisgor commented on src/partials/hero.html
> +  <h1 class="hero-title">
все огорнув, клас переніс

2024-02-08 05:01 UTC, gorisgor commented on src/css/hero.css
> +  font-family: 'Inter', sans-serif;
прибрав

2024-02-08 05:59 UTC, gorisgor commented
Зміни вніс, також додав медіа для текстів та посилання.

2024-02-08 07:41 UTC, Oleksandr-Karnaushenko commented on src/css/hero.css
>  @media screen and (min-width: 375px) {
оскільки ми робимо мабайл фірст то @media screen and (min-width: 375px)  можна не писати, у нас і так нічого не змінюється поки ми на планшет не перейдемо

2024-02-08 07:43 UTC, Oleksandr-Karnaushenko requested changes
прибрати перше медіа

2024-02-08 07:53 UTC, gorisgor commented
Прибрав

2024-02-08 10:05 UTC, Oleksandr-Karnaushenko approved these changes
ok

2024-02-08 10:55 UTC, tanyf5 approved these changes

2024-02-08 11:17 UTC, merged