Feature/footer
Oleksandr-Karnaushenko/Project-group-8 pull request #4
Opened 2024-02-07 20:07 UTC by tanyf5

2024-02-07 22:24 UTC, Oleksandr-Karnaushenko commented on src/partials/footer.html
> +    <div class="div-logo-nav-soc-m-footer">
я думаю що за таку довгу назву класу нас повішають))

2024-02-07 22:30 UTC, Oleksandr-Karnaushenko commented on src/partials/footer.html
> +              <svg width="19" height="19" class="cos-m-footer-list-icon">
тут напевно помилка у розмірах

2024-02-07 23:22 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  padding: 0 10px 0 10px;
прибрати цей падінг

2024-02-07 23:24 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
>  .footer {
можна на самому початку чи там уже де починаються медіа, дадати запит. 
@media screen and (min-width: 375px) {
  .footer.container {
    padding: 0 10px;
  }
}
щоб до 375 воно було гумове, а уже потім підлючався падінг, у нас це дає .контейнер, але так як у тебе менші падінги то потрібно зробити самому(

2024-02-07 23:32 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +.div-logo-nav-soc-m-footer {
додати width: 100%;

2024-02-07 23:32 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  padding: 40px 30px 20px 30px;
padding: 40px 30px 20px - такого запису вистачить
min-width: 355px; - не потрібен

2024-02-07 23:32 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +.footer.container {
описав вище

2024-02-07 23:32 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  flex-direction: row;
flex-direction: row; - по дефолту

2024-02-07 23:35 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  font-family: "Inter", sans-serif;
font-family: "Inter", sans-serif; - наслідуємо

2024-02-07 23:35 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  flex-direction: row;
flex-direction: row; - по дефолту

2024-02-07 23:35 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  font-family: "Inter", sans-serif;
font-family: "Inter", sans-serif; - наслідуємо

2024-02-07 23:36 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  flex-direction: row;
flex-direction: row; - по дефолту

2024-02-07 23:37 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  font-family: "Inter", sans-serif;
font-family: "Inter", sans-serif; - наслідуємо

2024-02-07 23:37 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  flex-direction: row;
flex-direction: row; - по дефолту

2024-02-07 23:38 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +.cos-m-footer-list-icon {
width: 24px;
  height: 24px;
наш ментор казав що такі речі безпосередньо записуються в html

2024-02-07 23:38 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  font-family: "Inter", sans-serif;
font-family: "Inter", sans-serif; - наслідуємо

2024-02-07 23:40 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +.privacy-policy {
дублюємо 6 строчок коду з попереднього класа, задати то все батькові

2024-02-07 23:41 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  .footer {
.footer.container

2024-02-07 23:42 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +    padding: 50px 48px 20px 48px;
padding: 50px 48px 20px - вистачить
min-width: 748px; - глобально маємо від .контейнера

2024-02-07 23:43 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +    flex-direction: row;
flex-direction: row; - по дефолту

2024-02-07 23:44 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  .footer {
.footer.container

2024-02-07 23:44 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +    padding: 50px 75px 20px 75px;
ширина з глобалки, в падінгу 3 значення

2024-02-07 23:45 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  .div-logo-nav-footer {
дублювання коду, залишити тільки геп

2024-02-07 23:46 UTC, Oleksandr-Karnaushenko commented on src/css/footer.css
> +  .div-logo-nav-soc-m-footer {
дублювання коду, залишити тільки геп

2024-02-07 23:48 UTC, Oleksandr-Karnaushenko requested changes
на доопрацювання

2024-02-08 10:05 UTC, tanyf5 commented on src/partials/footer.html
> +              <svg width="19" height="19" class="cos-m-footer-list-icon">
розміри взяті з макету, ікона інста дійсно відрізняється, замінити всі на 20х20?
https://prnt.sc/Avx_kEBrK3bo
https://prnt.sc/KwBeCurwHkz5
https://prnt.sc/xOYYvk54IrCu

2024-02-08 11:02 UTC, closed without merging