About us
Oleksandr-Karnaushenko/Project-group-8 pull request #6
Opened 2024-02-07 23:59 UTC by yarman777

2024-02-08 00:10 UTC, Oleksandr-Karnaushenko commented on src/partials/about-us.html
> +  <div class="about-us-content">
container перенести до класу about-us-content

2024-02-08 00:11 UTC, Oleksandr-Karnaushenko commented on src/partials/about-us.html
> +    <img
дописати alt=""

2024-02-08 00:14 UTC, Oleksandr-Karnaushenko commented on src/partials/about-us.html
дивно на макеті то виглядає, що перший дів заходить в картинку, пізніше буде тяжко то виставити.
особисто я б дав два діва. на контент та картинку. а на картинці дав би білий фон на дів і заокруглив саму картинку

2024-02-08 00:19 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +.about-us-content {
width: 335px; це ми маємо з глобального класа
height: 675px; таким краще взагалі не займатися)
max-width: 320px; пункт 1, і старайся слідкувати такі речі, width і max-width разом не має бути
padding-left: 20px;  padding-top: 40px;  padding-right: 20px; - на padding: 40px 20px;
  display: flex;  flex-direction: column; - там 3 блокових елемента, вони і так будуть один під одним

2024-02-08 00:21 UTC, Oleksandr-Karnaushenko requested changes
Підправити css і щось нада придумати з дівами

2024-02-08 18:46 UTC, yarman777 commented on src/partials/about-us.html
я вчора вже ліг спати. Не думав, що ти ще не спиш. Сьогодні обсудили. Вроді все зрозуміло=)буду працювати=)

2024-02-09 21:13 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  margin-bottom: 20px;
margin-bottom: 20px; не потрібний, ми його замінили гапом вище

2024-02-09 21:13 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  font-family: var(--font-family);
font-family: var(--font-family); у нас на усій сторінці Інтер, так що я думаю це можна поприбирати

2024-02-09 21:13 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +.about-us-description {
маржини погано впливають на адаптивність, тому ми їх прибираємо
  padding: 40px 0; - убиваємо 2 зайців 1 пострілом
  display: flex;
  flex-direction: column;
  gap: 20px;
оцим всим позбуваємося маждина далі

2024-02-09 21:14 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  display: block;
<p> і так блоковий елемент

2024-02-09 21:15 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  .about-us-descr-wrap {
padding: 50px 32px; - не зажимай текст падінгами, на то є кращий розв'язок

2024-02-09 21:17 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  .about-us-description {
margin-top: 50px; - видалити
   padding: 50px 0; - ті ж самі 2 зайця
    max-width: 389px; - а ось оцим ми обмежуємо текст

2024-02-09 21:18 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  .about-us-title {
max-width: 536px; - обмежуємо

2024-02-09 21:19 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  .about-us-description {
padding: 0; - він нам уже не потрібен
max-width: 354px; а- ось тут ти сам правильно обмежив, але чомусь не застосував то перед цим)

2024-02-09 21:21 UTC, Oleksandr-Karnaushenko requested changes
все супер, трішки відредагуй відступи а також повидаляй з css класи які не використовуєш
Та й буде готова секція)

2024-02-10 20:15 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +  .about-us-picture-wrap {
display: flex;
 justify-content: center;
щоб центрувалася каритнка

2024-02-10 20:16 UTC, Oleksandr-Karnaushenko commented on src/css/about-us.css
> +    padding: 50px;
там верху 50 а по боках 30

2024-02-10 20:17 UTC, Oleksandr-Karnaushenko requested changes
2 фікса і готово

2024-02-10 20:38 UTC, Oleksandr-Karnaushenko approved these changes

2024-02-10 20:38 UTC, merged